AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create an EC2 instance

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      InstanceType: t2.micro
      KeyName: mainkey 
      ImageId: ami-0e53db6fd757e38c7  # Update with the correct AMI ID
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
